# Generated by Django 4.1.6 on 2023-02-22 18:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('security_question_1', models.CharField(max_length=150)),
                ('security_question_1_answer', models.CharField(max_length=100)),
                ('security_question_2', models.CharField(max_length=150)),
                ('security_question_2_answer', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'Blog_Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
