# Generated by Django 4.1.6 on 2023-02-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_users',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='blog_users',
            name='security_question_1',
        ),
        migrations.RemoveField(
            model_name='blog_users',
            name='security_question_1_answer',
        ),
        migrations.RemoveField(
            model_name='blog_users',
            name='security_question_2',
        ),
        migrations.RemoveField(
            model_name='blog_users',
            name='security_question_2_answer',
        ),
    ]
