# Generated by Django 4.1.6 on 2023-02-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_blog_users_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Users',
        ),
    ]
