# Generated by Django 4.1.6 on 2023-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=60)),
                ('blog_description', models.TextField()),
                ('made_date', models.DateField()),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, choices=[(True, 'True'), (False, 'False')], default=True)),
            ],
        ),
    ]
