# Generated by Django 4.1.6 on 2023-02-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_blogs',
            table='User_Blogs',
        ),
    ]
