# Generated by Django 4.1.6 on 2023-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_user_blogs_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_blogs',
            name='made_date',
            field=models.DateField(blank=True),
        ),
    ]
